<?php

namespace App\Http;

use App\Database\DatabaseModule;
use Dybasedev\Keeper\Http\HttpServices\KeeperHttpService;
use Illuminate\Container\Container;
use Swoole\Http\Server as SwooleHttpServer;
use App\Supports\Log\Log;

class Service extends KeeperHttpService
{
    public function init(SwooleHttpServer $server, $workerId)
    {
        parent::init($server, $workerId); // TODO: Change the autogenerated stub
        
        Log::info('inti', [$workerId]);
        
        
    }
    
    public function destroy(SwooleHttpServer $server, $workerId)
    {
        parent::destroy($server, $workerId); // TODO: Change the autogenerated stub
        
        
    }
}